# Postgres, and the thing stock NixOS cannot do at all: more than one of it.
#
# `services.postgresql` is a singleton option path. Any floe that emits it is
# single-instance no matter what the linker permits — two instances would write
# the same path and NixOS would refuse the conflicting definitions. So a
# genuinely multi-instance floe does not use that module. It emits its own
# systemd unit, its own user, its own group and its own tmpfiles rule, every one
# of them keyed by `config.floe.name` — the name the *link* gave this instance.
#
# That is the real cost of multi-instance: this file is the nixpkgs postgresql
# module's job, done again. It is also the whole benefit, and there is no
# version of it that keeps both.
#
# Note which namespaces it writes and which it does not. It writes
# `systemd.services.<unique>` and `users.users.<unique>` directly, and nothing
# owns those — because an attrset keyed by a unique name is disjoint by
# construction, so many writers cannot collide. It does *not* write
# `networking.firewall`, because a port list merges by policy rather than by
# key, and that is the kind of namespace that needs an owner.
{
  lib,
  floe,
  sigs,
  kinds,
}:

let
  T = floe.T;
in
floe.mkFloe {
  name = "postgres";
  summary = "One PostgreSQL instance, named by the link, alongside any others.";

  inputs = {
    port = lib.mkOption {
      type = lib.types.port;
      default = 5432;
      description = "Port this instance listens on. Two instances need two ports.";
    };
    package = lib.mkOption {
      type = lib.types.str;
      default = "/run/current-system/sw";
      description = "Prefix the server binary is found under.";
    };
  };

  provides = {
    ports = sigs.PORT_CLAIM;
    database = sigs.DATABASE;
  };

  out.nixosConfig = kinds.nixosConfig (
    T.record {
      systemd = T.record {
        services = T.attrsOf (
          T.record {
            description = T.str;
            wantedBy = T.listOf T.str;
            serviceConfig = T.attrsOf T.str;
          }
        );
        tmpfiles = T.record { rules = T.listOf T.str; };
      };
      users = T.record {
        users = T.attrsOf (
          T.record {
            isSystemUser = T.bool;
            group = T.str;
            home = T.str;
          }
        );
        groups = T.attrsOf (T.record { });
      };
    }
  );

  body =
    {
      inputs,
      requires,
      collects,
      floe,
    }:
    let
      # The link's name for this instance. Everything below is keyed by it, and
      # that is the only reason two of these can coexist.
      inst = floe.name;
      svc = "postgres-${inst}";
      dataDir = "/var/lib/${svc}";
      # In the state directory, not /run: a Postgres password has to survive a
      # reboot or the stored role no longer matches. It is also per-instance, so
      # two instances never contend for one path — which `/run/secrets` shared
      # between them would have done.
      passwordFile = "${dataDir}/password";
      inherit (inputs) port package;
    in
    {
      provides.ports.tcp = [ port ];

      provides.database = {
        host = "127.0.0.1";
        inherit port passwordFile;

        # Generated by this floe's own ExecStartPre, below. A consumer that
        # interpolates it into NixOS config gets an eval error naming this
        # instance as the source — and with two instances, naming *which* one.
        #
        # This floe offers both halves, which is the realistic shape: `passwordFile`
        # is the location, concrete at eval and usable by a systemd unit's
        # `LoadCredential`; `password` is the secret, which no eval-time consumer
        # may read. A consumer that needs to *pass* a credential takes the path and
        # needs no backend at all. One that needs the value itself — rendering it
        # into a config file — needs a backend, and the retrieval tells it how.
        password = floe.mkDeferred sigs.FILE_REF {
          path = passwordFile;
          mode = "firstLine";
        };
      };

      out.nixosConfig = {
        systemd = {
          services.${svc} = {
            description = "PostgreSQL (${inst}) on port ${toString port}";
            wantedBy = [ "multi-user.target" ];
            serviceConfig = {
              Type = "notify";
              User = svc;
              Group = svc;
              StateDirectory = svc;

              # What makes `passwordFile` more than a string. Generated once, on
              # first start, 0600 and owned by this instance — and idempotent, so
              # a restart does not invalidate the role.
              #
              # In a real system this is where sops-nix or systemd-creds would go
              # instead. The point for the example is that *something* in the link
              # writes the file a consumer's LoadCredential reads, and a test
              # asserts those two paths are the same string.
              ExecStartPre =
                "${package}/bin/sh -c 'test -s ${passwordFile} || "
                + "(umask 077; ${package}/bin/head -c 32 /dev/urandom | "
                + "${package}/bin/base64 > ${passwordFile})'";

              ExecStart = "${package}/bin/postgres -D ${dataDir} -p ${toString port}";
            };
          };
          # A list, so two instances' rules concatenate. That is correct here:
          # the rules name different directories.
          tmpfiles.rules = [ "d ${dataDir} 0700 ${svc} ${svc} - -" ];
        };

        users = {
          users.${svc} = {
            isSystemUser = true;
            group = svc;
            home = dataDir;
          };
          groups.${svc} = { };
        };
      };
    };
}
