# Postgres. A contributor that owns its own namespace and shares nothing else.
#
# Two things to notice. Its DATABASE provide omits `dataDir`, which it plainly
# knows — a consumer that wants it has to ask for the signature to be widened,
# rather than reading `config.services.postgresql.dataDir` behind its back. And
# its password is `T.deferred`: the path is known at eval, the secret is not.
{
  lib,
  floe,
  sigs,
  kinds,
}:

let
  T = floe.T;
  passwordFile = "/run/secrets/postgres-password";
in
floe.mkFloe {
  name = "postgres";
  summary = "PostgreSQL, reachable on the local machine and claimed on the LAN.";

  inputs.port = lib.mkOption {
    type = lib.types.port;
    default = 5432;
    description = "Port to listen on.";
  };

  provides = {
    ports = sigs.PORT_CLAIM;
    database = sigs.DATABASE;
  };

  out.nixos = kinds.nixosConfig (
    T.record {
      services = T.record {
        postgresql = T.record {
          enable = T.bool;
          enableTCPIP = T.bool;
          settings = T.record { port = T.int; };
        };
      };
    }
  );

  modules = [
    (
      # `floe` here is the specialArg the linker injects, not the library this
      # file was passed — it carries `mkDeferred`, bound to this unit's name.
      { config, floe, ... }:
      let
        inherit (config.floe.inputs) port;
      in
      {
        config.floe.provides.ports.tcp = [ port ];

        config.floe.provides.database = {
          host = "127.0.0.1";
          inherit port passwordFile;

          # Generated by the service on first start. The token records that,
          # and where it came from, so a consumer using it as though it were a
          # string is an error at eval naming this floe.
          password = floe.mkDeferred [
            "postgres"
            "password"
          ];
        };

        config.floe.out.nixos.services.postgresql = {
          enable = true;
          enableTCPIP = true;
          settings = { inherit port; };
        };
      }
    )
  ];
}
